### ISSUE TITLE
Renewal

### ISSUE THREAD

**Issue by nikolai-b** [WharfChambers/wharfmembers#7]
Add renewal or new member option.

On renewal offer to membership number or email.

On failure:
Sorry, we could not find you in our database.

On success:
Thank you [membership number] / [email] please come to the bar to pay (text to be confirmed)

**Comment by wharfchambersdb** [comment]
On failure: Sorry, we could not find you in our database. Please submit your details through the main form. Thanks

On success: Thank you [membership number], please speak to a member of staff next time you're in to finalise your renewal
